### ISSUE TITLE
NO_IN_SCOPE_TABLE message, cant download private scope 

### ISSUE THREAD

**Issue by ipk1** [sw33tLie/bbscope#10]
Hey,

while running  it with these options for bugcrowd -b -p -o t, NO_IN_SCOPE_TABLE is being displayed for all the results.

regards
ipk

**Comment by sw33tLie** [comment]
Hey @ipk1 , I actually have released a fix yesterday for this.
Can you please test the latest version and tell me if you still notice that?
Thanks!

**Comment by ipk1** [comment]
Hey @sw33tLie , still seeing the same issue
thanks

**Comment by sw33tLie** [comment]
Hmm, that's weird, works here and also works for a few friends I asked to try it.
Sorry to say this again but just to be 100% sure, are you actually using the most recent version?
You can be sure to install that one by running:
```go install https://sw33tLie/bbscope@d405930ac00ccd0e4087aa6294f58a9d10ab6660```

Let me know :)

**Comment by ipk1** [comment]
Hey, deleting and reinstalling worked!!!!, may be i messed up with the version :) however when i use -b -p , a few non rewarding programs are listed too

thanks
