### ISSUE TITLE
Wrong results for bugcrowd private programs

### ISSUE THREAD

**Issue by Phoenix1112** [sw33tLie/bbscope#17]
hello... thanks for this project. When I want to pull private programs in the bugcrowd program, missing results and more than one same subdomain belonging to a program appear. When I look at the bbscope results, I see 3 *.blabla.com results. I guess it adds the same subdomain addresses to more than one output. Also, I can't see all the programs belonging to my private programs in the output.

my command:

```
bbscope bc -t bugcrowd-cookie -b -p -o tu
```

**Comment by sw33tLie** [comment]
Hello,
indeed there's something wrong going on.
I'll fix this shortly :)
