### ISSUE TITLE
Too many open files error

### ISSUE THREAD

**Issue by ghost** [sw33tLie/bbscope#20]
Hi @sw33tLie  Please help me resolve the below issue.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/86880819/172971308-9b30fa9d-7c80-4dc1-847f-624984456917.png">

**Comment by rasiras** [comment]
any fix for this ? @sw33tLie

**Comment by ndelphit** [comment]
Hey @daai1, @rasiras 
I had the same problem with `h1`.
Here is a quick fix that helped me:
```sh
git clone https://github.com/sw33tLie/bbscope.git
cd ./bbscope
git checkout 20dd275e1255244f7f8cb6e728eedcb283516ca1
go build
./bbscope
```

**Comment by sw33tLie** [comment]
Hi there, I believe this is related to your machine config.
You can either:
- reduce concurrency
- increase file descriptors (ulimit -n flag)

Hope this helps :)
