### ISSUE TITLE
2022/10/21 17:48:03 Invalid print flag

### ISSUE THREAD

**Issue by knowthetech** [sw33tLie/bbscope#22]
2022/10/21 17:48:03 Invalid print flag

**Comment by sw33tLie** [comment]
Hello,
I believe you're using the tool wrong.
Can you please post the command you tried?

**Comment by knowthetech** [comment]
bbscope h1 -t "token" -u "uname" -b -o bounty.txt;

**Comment by knowthetech** [comment]
got it solved
