### ISSUE TITLE
No feedback after operation for bugcrowd

### ISSUE THREAD

**Issue by 0x7e-1sq** [sw33tLie/bbscope#24]
Why is there no feedback after I run according to the document
Here is a screenshot of my operation
thanks

![image](https://user-images.githubusercontent.com/57382546/197775972-be30be2c-8611-4d06-a029-8c3670cc76c6.png)

**Comment by sw33tLie** [comment]
Usually it takes a while, you can check if something is going wrong by using the --proxy flag to send traffic to burp suite and inspect the requests.

Thanks
