### ISSUE TITLE
immunefi unexpected EOF

### ISSUE THREAD

**Issue by molitona** [sw33tLie/bbscope#29]
> bbscope immunefi -c web -b                                                                                                     
2023/03/10 11:52:11 HTTP request failed: Get "https://immunefi.com/bounty/zksync/": unexpected EOF

**Comment by dhruvvyas25** [comment]
HTTP request failed: Get "https://immunefi.com/bounty/morpho/": net/http: TLS handshake timeout

**Comment by sw33tLie** [comment]
I believe this is an issue with the default concurrency level which was set to 40. Apparently that's too high, I lowered it.

**Comment by dhruvvyas25** [comment]
It works, thanks
