### ISSUE TITLE
Intigriti URL endpoint has changed

### ISSUE THREAD

**Issue by horise** [sw33tLie/bbscope#31]
Hi, 
Using the default hard coded intigriti URL endpoint, I can get nothing from intigriti.

After checking the http request traffic, I found that the Intigriti URL endpoint has changed to:
        INTIGRITI_PROGRAMS_ENDPOINT     = "https://api.intigriti.com/core/researcher/programs"
        INTIGRITI_PROGRAM_BASE_ENDPOINT = "https://api.intigriti.com/core/researcher/programs"

I have tested on my side, manually update the source code "github.com/bbscope/pkg/platforms/intigriti/intigriti.go",  will fix this issue.
![intigriti](https://user-images.githubusercontent.com/50666236/235071099-66662157-e478-4b4f-b75c-6a5096444b28.png)

**Comment by sw33tLie** [comment]
Thank you!
