### ISSUE TITLE
not working with intigriti

### ISSUE THREAD

**Issue by knowthetech** [sw33tLie/bbscope#33]
not fetching intigriti calls nowadays please check

**Comment by albinowax** [comment]
Yep, looks like they don't use the authorisation header any more.

**Comment by 0xdln1** [comment]
@albinowax yeah, there is no bearer token anymore

**Comment by albinowax** [comment]
@0xdln1 it's fixed in the latest release now

**Comment by sw33tLie** [comment]
Hey guys,
sorry for not replying to this issue earlier, as @albinowax said I fixed it in the latest release :)
Thanks!
