### ISSUE TITLE
Bugcrowd's private programs are not being fetched

### ISSUE THREAD

**Issue by 0xdln1** [sw33tLie/bbscope#39]
bbscope is not fetching bugcrowd's private programs even if we use the -p flag it only returns the public programs

Command used:

```bash
bbscope bc -t "token" -b -o tdu -d ', ' -p
```

![image](https://github.com/sw33tLie/bbscope/assets/83292788/1c0a5b59-c87a-4798-b103-047cbe3ef091)

**Comment by sw33tLie** [comment]
Apparently bugcrowd doesn't use the accepted_invite[] program anymore in the /programs.json endpoint.
I don't see an easy way to fix this but I'll try to fix it

**Comment by sw33tLie** [comment]
already done that :)

**Comment by 0xdln1** [comment]
Thanks @sw33tLie for instant fix
