### ISSUE TITLE
Bugcrowd email+password login is broken

### ISSUE THREAD

**Issue by sw33tLie** [sw33tLie/bbscope#40]
I am aware that the login workflow with bugcrowd doesn't work right now.
This is due to recent platform changes that moved the authentication to identity.bugcrowd.com.

Please use the _bugcrowd_session token as of now and pass it to the -t flag in bbscope bc.

Thanks

**Comment by molitona** [comment]
the tool doesn't fetch private programs on BC @sw33tLie

**Comment by molitona** [comment]
its not reliable at all over 20 private and public ones the tool didn't catch..

**Comment by sw33tLie** [comment]
Hey @molitona, can you share here one public program that the tool didn't catch?
Thank you :)

**Comment by molitona** [comment]
oh sorry @sw33tLie  after re-checking they were "Joinable ones" not public but, for private programs (invite+joinable) the tool didn't catch +20 of them yesterday, what reason?

**Comment by sw33tLie** [comment]
Hey, I don't see any obvious reason as of now.
Do you have telegram/discord/twitter so that we can find out why this happens privately?

Thanks

**Comment by sw33tLie** [comment]
Hi, this should be fixed

**Comment by molitona** [comment]
hello @sw33tLie ,

sorry for late resp

with _bugcrowd_session lastest version

https://bugcrowd.com/bugcrowd
https://bugcrowd.com/foxycart
https://bugcrowd.com/freedomofpress
https://bugcrowd.com/statuspage
https://bugcrowd.com/whmcs

are not catched

used cmd:

bbscope bc -b -o u -t "XXX"

**Comment by sw33tLie** [comment]
Hi,
there was an issue when iterating through the handle pages, sometimes the bugcrowd API doesn't return the correct total pages so I've changed the code and i don't trust that number anymore.

Could you check if now you get more programs?

**Comment by molitona** [comment]
it works fine now, all programs fetched. thanks!
