### ISSUE TITLE
New issue on Bugcrowd

### ISSUE THREAD

**Issue by zy9ard3** [sw33tLie/bbscope#49]
Hey @sw33tLie 

Hope you're doing well !!

Bugcrowd has restructed and launched new program page and some of the programs have been opted for this and migrated to this page

Unfortunately, these pages are currently being missed by bbscope

Run bbscope and you may notice that the following programs are not being fetched
* https://bugcrowd.com/engagements/caffeine
* https://bugcrowd.com/engagements/immutable
* https://bugcrowd.com/engagements/planethosterinc
* https://bugcrowd.com/engagements/tyler-tech-data-insights

Thanks & Regards,
@zy9ard3

**Comment by sw33tLie** [comment]
Hi, indeed it looks like you're right.
Will try to fix this asap :)

**Comment by leetIbrahim** [comment]
Does it fixed?

**Comment by sw33tLie** [comment]
Hi, i'm sorry I have been pretty busy.
Working on a fix right now

**Comment by sw33tLie** [comment]
Hello @zy9ard3 @leetIbrahim, can you please try the latest version?
I believe I fixed this, however, I'm not 100% sure I handled all the edge cases so I'd like your feedback.

Thanks!

**Comment by leetIbrahim** [comment]
Works fine for me, thank you

**Comment by zy9ard3** [comment]
Thanks @sw33tLie, Works well : )

**Comment by sw33tLie** [comment]
Thank you both!
