### ISSUE TITLE
BC sope

### ISSUE THREAD

**Issue by ipk1** [sw33tLie/bbscope#5]
hi,
I am not a GO expert but played around with your code i noticed that by replacing "react-component-researcher-target-groups"  to ".cc-rewards-link-table__endpoint" in bugcrowd.go yields more results, kindly have look.

thanks

**Comment by sw33tLie** [comment]
Thanks for opening this issue, appreciate it!
I'll check it out shortly :)

**Comment by sw33tLie** [comment]
Hi again @ipk1, apologies for the delay.
I tried to change the code according to what you said but now it's not finding anything at all.
Just to make sure, you changed like 91 to something like this, right?
```
doc.Find(".cc-rewards-link-table__endpoint").Each(func(index int, s *goquery.Selection) {
```
Did you change anything else to make the code work?
Thanks

**Comment by ipk1** [comment]
Hey,
yeah i changed that to ".cc-rewards-link-table__endpoint" , it works for me however i changed in the forked version, you can have a look at https://github.com/ipk1/test/ , I might have changed something else not sure exactly ... sorry

thanks

**Comment by sw33tLie** [comment]
Hey there, apologies for not replying earlier.
I took a look at the code and I believe that now it works much better for bugcrowd, finding more scope elements.
Let me know if you still have issues or not :)
Thanks
