### ISSUE TITLE
getting URL from anchor tag of scope- Bugcrowd stopped working

### ISSUE THREAD

**Issue by proabiral** [sw33tLie/bbscope#54]
The fix to get URL from anchor tag of Bugcrowd scope is not working. It seems like something from Bugcrowd's end changed.

https://github.com/sw33tLie/bbscope/commit/99fef9fe7a3f6eace1b2d03ec2abc8cefe1c0c1f

![Screenshot 2024-05-28 at 12 46 23](https://github.com/sw33tLie/bbscope/assets/22173232/3a6601a9-2efe-4fac-91e7-b27ecc4fe16b)

This should have pulled the link `https://central.sophos.com/` instead of text `Sophos Central`

![image](https://github.com/sw33tLie/bbscope/assets/22173232/ffcfe59c-48d6-40ad-b42e-820caa52a96a)

**Comment by sw33tLie** [comment]
Turns out it wasn't a Bugcrowd change but a bug I introduced.
Thanks for reporting this! :)
