### ISSUE TITLE
Bugcrowd bbpOnly filter doesn't work

### ISSUE THREAD

**Issue by hakluke** [sw33tLie/bbscope#6]
I noticed that some of the programs that I picked up with bbscope are VDPs even though I specified the `-b` flag.

Reproduction:

`bbscope bc -b -l -u -t TOKEN`

Observe that VDP programs are included in the list such as "https://bugcrowd.com/netgearkudos".

**Comment by sw33tLie** [comment]
Hi @hakluke ,
thank you for sending this issue.
It looks like you're right, apparently this happens for VDP programs that don't have a scope table.
Will fix this soon :)

**Comment by sw33tLie** [comment]
Nevermind, this happens because Bugcrowd has recently stopped giving points for VDPs and they renamed the `points-only` GET parameter to `vdp`.
Just committed the fix!

Also note that new bbscope versions use a different output flag:
```
bbscope bc -t TOKEN -b -o tu
```

Thank you again for the heads up!

**Comment by hakluke** [comment]
Wow quick fix, love your work! 💚🎉
