### ISSUE TITLE
invalid username or token error?

### ISSUE THREAD

**Issue by Phoenix1112** [sw33tLie/bbscope#7]
hello. thanks for this project.. i did create api token on hackerone.. 

this is my bbscope command:

bbscope h1 -t "token-here" -b -o t

but after doing this i get "invalid username or token" error.

![invalid](https://user-images.githubusercontent.com/42475284/125988896-83d1bf09-5ec4-4c4f-8fcc-01e246ecbfa1.png)

**Comment by Phoenix1112** [comment]
i understand to problem. The image below is taken from the bbscope homepage. I used one of the commands used on the main page when reporting the problem above. But what is missing from the commands on your homepage is the -u parameter. After adding the hackerone username along with the -u parameter to the command, bbscope did not give any error. please rearrange the command on your homepage.


![image](https://user-images.githubusercontent.com/42475284/125989412-4293e6be-eb95-49f4-ac6e-026eedc275aa.png)

**Comment by sw33tLie** [comment]
Hi there, thanks for opening this issue.
You're absolutely right, the username flag is now mandatory for h1 and we definitely can make it more obvious for our users.
Working on this very soon :)
