### ISSUE TITLE
Bugcrowd. Fetches only first scope table

### ISSUE THREAD

**Issue by Sh1Yo** [sw33tLie/bbscope#8]
Some programs do have a second or even third scope table but the tool fetches only the first one. For example: https://bugcrowd.com/ibotta has two scope tables and while the tool perfectly fetches the first table (In Scope Targets : Mobile and API) It fails to find the second table (In Scope Targets: Web Target).

Command I've used:
```bash
bbscope bc -t U..2 -o tu
```

Output (only the first table is present):
```
Chrome Extension https://bugcrowd.com/ibotta
http://market.android.com/details?id=com.ibotta.android https://bugcrowd.com/ibotta
http://itunes.apple.com/us/app/ibotta/id559887125 https://bugcrowd.com/ibotta
https://content-server.ibotta.com/graphql https://bugcrowd.com/ibotta
https://api.ibotta.com https://bugcrowd.com/ibotta
https://api.ibops.net https://bugcrowd.com/ibotta
https://api.int.ibops.net https://bugcrowd.com/ibotta
https://api.int.ibops.net/customer-loyalty-service https://bugcrowd.com/ibotta
 https://api.ibops.net/ad-management https://bugcrowd.com/ibotta
Ibotta App Data & Memory https://bugcrowd.com/ibotta
```

**Comment by sw33tLie** [comment]
Hello, I believe I've fixed this issue.
Let me know if it works for you as well :)
Thanks!

**Comment by Sh1Yo** [comment]
Looks like it works now, thanks.
